name: CI

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  xcode-build:
    name: Xcode Build
    runs-on: macOS-11
    strategy:
      matrix:
        platform: ['iOS_14', 'iOS_13']
      fail-fast: false
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Bundle Install
        run: bundle install --gemfile=Example/Gemfile
      - name: Select Xcode Version (12.5.1)
        run: sudo xcode-select --switch /Applications/Xcode_12.5.1.app/Contents/Developer
        if: matrix.platform == 'iOS_14'
      - name: Prepare Simulator Runtimes
        run: Scripts/github/prepare-simulators.sh ${{ matrix.platform }}
      - name: Pod Install
        run: bundle exec --gemfile=Example/Gemfile pod install --project-directory=Example
      - name: Build and Test
        run: Scripts/build.swift xcode ${{ matrix.platform }} `which xcpretty`
      - uses: EndBug/add-and-commit@v9
        if: failure()
        with:
          add: 'Example'
          message: 'Update ${{ matrix.platform }} snapshots'
          author_name: 'github-actions[bot]'
          author_email: actions@github.com
          pull: '--rebase --autostash'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Results
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: Test Results
          path: .build/derivedData/**/Logs/Test/*.xcresult
  pod-lint:
    name: Pod Lint
    runs-on: macOS-11
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Bundle Install
        run: bundle install --gemfile=Example/Gemfile
      - name: Pod Install
        run: bundle exec --gemfile=Example/Gemfile pod install --project-directory=Example
      - name: Lint Podspec
        run: bundle exec --gemfile=Example/Gemfile pod lib lint --verbose --fail-fast
  spm:
    name: SPM Build
    runs-on: macOS-11
    strategy:
      matrix:
        platform: ['iOS_14']
      fail-fast: false
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Select Xcode Version (12.5.1)
        run: sudo xcode-select --switch /Applications/Xcode_12.5.1.app/Contents/Developer
      - name: Build
        run: Scripts/build.swift spm ${{ matrix.platform }}
